-- ½ÃÄö½º »èÁ¦
drop sequence BOARD_BOARD_NUM_SEQ;
drop sequence SHELTER_CODE_SEQ;
DROP SEQUENCE NOSE_PRINT_NOSE_PRINT_NUM_SEQ;
DROP SEQUENCE COMMENTS_COMMENT_NUM_SEQ;
DROP SEQUENCE MATCHING_RESULT_NUM_SEQ ;

-------------------------------------------------------------------------------------------------------
DROP TABLE BOARD CASCADE CONSTRAINT;
DROP TABLE MEMBER CASCADE CONSTRAINT;
DROP TABLE SHELTER_INFO CASCADE CONSTRAINT;
DROP TABLE MEMBER CASCADE CONSTRAINT;
DROP TABLE NOSE_PRINT CASCADE CONSTRAINT;
DROP TABLE MATCHING_RESULT CASCADE CONSTRAINT;
DROP TABLE COMMENTS CASCADE CONSTRAINT;
DROP TABLE PRED_KIND CASCADE CONSTRAINT;
DROP TABLE ADOPTION CASCADE CONSTRAINT;
----------------------------------------------------------------------------------------------------------------
--½ÃÄö½º »ý¼º
CREATE SEQUENCE SHELTER_CODE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BOARD_BOARD_NUM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE NOSE_PRINT_NOSE_PRINT_NUM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MATCHING_RESULT_NUM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COMMENTS_COMMENTS_NUM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADOPTION_ADP_NUM_SEQ START WITH 1 INCREMENT BY 1;
------------------------------------------------------------------------------------
MEMBER 

CREATE TABLE MEMBER(
  ID VARCHAR(50),
  PW VARCHAR(50) NOT NULL, 
  NAME VARCHAR(50) NOT NULL,
  MEMBER_CODE NUMBER NOT NULL,
  TEL NUMBER NOT NULL,
  ADDRESS VARCHAR(50) NOT NULL,
  CONSTRAINT MEMBER_ID_PK PRIMARY KEY(ID)
);


----------------------------------------------------------------------------------------------
SHELTER_INFO

CREATE TABLE SHELTER_INFO(
  SHELTER_CODE NUMBER,
  SHELTER_AREA VARCHAR2(50) NOT NULL, 
  SHELTER_ADDRESS VARCHAR2(50) NOT NULL,
  SHELTER_TEL NUMBER NOT NULL,
  CONSTRAINT SHELTER_CODE_PK PRIMARY KEY(SHELTER_CODE) 
);


----------------------------------------------------------------------------------------------
BOARD

CREATE TABLE BOARD (
   BOARD_NUM NUMBER,
   ID VARCHAR(50) NOT NULL,
   BOARD_TYPE NUMBER NOT NULL,
   STATUS NUMBER NOT NULL,
   PICTURE VARCHAR(500) NOT NULL,
   GENDER VARCHAR(50) NOT NULL,
   AGE NUMBER,
   COLOR VARCHAR(50) NOT NULL,
   KIND VARCHAR(50) NOT NULL,
   WEIGHT NUMBER,
   NOTICE VARCHAR(50),
   MISSING_DATE DATE,
   MISSING_TIME DATE,
   SHELTER VARCHAR(500),
   PLACE VARCHAR(500) NOT NULL,
   TEL VARCHAR(500) NOT NULL,
   CONTENT VARCHAR(500) NOT NULL,
   CONSTRAINT BOARD_NUM_PK PRIMARY KEY(BOARD_NUM),
   CONSTRAINT BOARD_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER(ID)
);


----------------------------------------------------------------------------------------------

NOSE_PRINT 

CREATE TABLE NOSE_PRINT(
  NOSE_PRINT_NUM NUMBER,
  ID VARCHAR(50) NOT NULL, 
  DOG_NAME VARCHAR(50) NOT NULL,
  DOG_NOSE_PRINT VARCHAR(500) NOT NULL,
  DOG_BREEDS VARCHAR(50) NOT NULL,
  DOG_GENCER VARCHAR(50) NOT NULL, 
  CONSTRAINT NOSE_PRINT_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID),
  CONSTRAINT NOSE_PRINT_NOSE_PRINT_NUM_PK PRIMARY KEY (NOSE_PRINT_NUM) 
);


-----------------------------------------------------------------------------------------------------------------
MATCHING_RESULT 

CREATE TABLE MATCHING_RESULT(
  RESULT_NUM NUMBER,
  ID VARCHAR(50) NOT NULL,
  BOARD_NUM1 NUMBER NOT NULL,
  BOARD_NUM2 NUMBER NOT NULL,
  CONSTRAINT MATCHING_RESULT_RESULT_NUM_PK PRIMARY KEY (RESULT_NUM)
  
);

-----------------------------------------------------------------------------------------------------------------
COMMENTS

CREATE TABLE COMMENTS(
  COMMENTS_NUM NUMBER,
  BOARD_NUM NUMBER NOT NULL,
  ID VARCHAR2(50) NOT NULL,
  COMMENTS VARCHAR(500) NOT NULL,
  CONSTRAINT COMMENTS_COMMENTS_NUM_PK PRIMARY KEY (COMMENTS_NUM), 
  CONSTRAINT COMMENTS_COMMENTS_BOARD_NUM_FK FOREIGN KEY(BOARD_NUM) REFERENCES BOARD(BOARD_NUM)
);
 
 -----------------------------------------------------------------------------------------------------------------
ADOPTION

CREATE TABLE ADOPTION(
  ADP_NUM NUMBER,
  ADP_PICTURE VARCHAR(50) NOT NULL,
  ADP_GENDER VARCHAR(50) NOT NULL,
  ADP_COLOR VARCHAR(500) NOT NULL,
  ADP_STATUS VARCHAR(50) NOT NULL,
  ADP_AGE VARCHAR(50) NOT NULL,
  ADP_SHELTER VARCHAR(500) NOT NULL,
  ADP_ADDR VARCHAR(500) NOT NULL,
  ADP_TEL VARCHAR(500) NOT NULL,
  ADP_WEIGHT NUMBER NOT NULL,
  ADP_CONTENT VARCHAR(500) NOT NULL,
  CONSTRAINT ADOPTION_ADP_NUM_PK PRIMARY KEY (ADP_NUM)
);

  -----------------------------------------------------------------------------------------------------------------
PRED KIND 

CREATE TABLE PRED_KIND (
  ID VARCHAR(50),
  TIME DATE  NOT NULL,
  FILENAME VARCHAR(500) NOT NULL,
  PRED_KIND VARCHAR(50) NOT NULL,
  CONSTRAINT PRED_KIND_ID_PK PRIMARY KEY (ID)
);
select * from member;
